// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNQY1FhnINTSjWNnGCEDyIuuYeDTbJhPI',
    appId: '1:429388539704:android:3762f8e6eb49ec52bc03cd',
    messagingSenderId: '429388539704',
    projectId: 'thuoc-lo-ban-app',
    storageBucket: 'thuoc-lo-ban-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-I0CbAudXvi7Yk4u4M1yRDYCI_rij70Y',
    appId: '1:429388539704:ios:e2276115c46d1050bc03cd',
    messagingSenderId: '429388539704',
    projectId: 'thuoc-lo-ban-app',
    storageBucket: 'thuoc-lo-ban-app.firebasestorage.app',
    iosBundleId: 'com.example.thuocLoBanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-I0CbAudXvi7Yk4u4M1yRDYCI_rij70Y',
    appId: '1:429388539704:ios:e2276115c46d1050bc03cd',
    messagingSenderId: '429388539704',
    projectId: 'thuoc-lo-ban-app',
    storageBucket: 'thuoc-lo-ban-app.firebasestorage.app',
    iosBundleId: 'com.example.thuocLoBanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmqm0hEzZvmtu6x2dtxEkhoUj3Mq5bO7o',
    appId: '1:429388539704:web:f34a4fff806fbe75bc03cd',
    messagingSenderId: '429388539704',
    projectId: 'thuoc-lo-ban-app',
    authDomain: 'thuoc-lo-ban-app.firebaseapp.com',
    storageBucket: 'thuoc-lo-ban-app.firebasestorage.app',
  );
}
